# that is just a test-setup for development of the image and different tests - change it for your needs
version: "2"

services:
  traefik:
    image: eugenmayer/traefik
    container_name: traefik
    volumes:
      - ./tiller:/etc/tiller
    environment:
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_HTTPS_ENABLE: 'true'
      TRAEFIK_HTTPS_ENABLE: 'true'
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_CHALLENGE: 'dns'
      TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER: "cloudflare"
      TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS: 'CF_MAIL=aasdas@gmx.de;CF_API=adqweq121'
      TRAEFIK_RANCHER_ENABLE: 'true'
    ports:
      - 80:8080
      - 443:8443
      - 8000:8000

volumes:
  acme:
    driver: local
  certs:
    driver: local
  filestorage:
    driver: local